/**
 * YouTube Research Service
 *
 * Provides high-level YouTube research functionality including
 * video search, channel search, data analysis, and report generation.
 */

import { YouTubeAPIClient } from './client';
import type {
  VideoSearchResult,
  VideoInfo,
  ChannelSearchResult,
  AnalysisResult,
} from './types';

export class YouTubeResearchService {
  private client: YouTubeAPIClient;

  constructor(apiKey?: string) {
    this.client = new YouTubeAPIClient(apiKey);
    console.log('YouTubeResearchService initialized');
  }

  /**
   * Search for YouTube videos
   * @param query - Search query string
   * @param maxResults - Maximum number of results (default: 10)
   * @param period - Time period filter (day, week, month, year, all)
   * @returns Promise with search results
   */
  async searchVideos(query: string, maxResults = 10, period = 'all'): Promise<VideoSearchResult[]> {
    console.log(`Searching videos: ${query} (period: ${period})`);
    return await this.client.searchVideos(query, maxResults, period);
  }

  /**
   * Get video information
   * @param videoId - YouTube video ID
   * @returns Promise with video data
   */
  async getVideoInfo(videoId: string): Promise<VideoInfo> {
    console.log(`Getting video info: ${videoId}`);
    return await this.client.getVideoInfo(videoId);
  }

  /**
   * Search for YouTube channels
   * @param query - Search query string
   * @param maxResults - Maximum number of results (default: 10)
   * @returns Promise with channel results
   */
  async searchChannels(query: string, maxResults = 10): Promise<ChannelSearchResult[]> {
    console.log(`Searching channels: ${query}`);
    return await this.client.searchChannels(query, maxResults);
  }

  /**
   * Analyze video data
   * @param videos - Array of video data to analyze
   * @returns Analysis results
   */
  analyzeData(videos: VideoInfo[]): AnalysisResult {
    console.log(`Analyzing data for ${videos.length} videos`);

    if (videos.length === 0) {
      return {
        totalVideos: 0,
        averageViews: 0,
        topVideos: [],
        trends: [],
      };
    }

    const totalViews = videos.reduce((sum, video) => sum + video.viewCount, 0);
    const averageViews = Math.round(totalViews / videos.length);

    // Sort by view count and get top videos
    const topVideos = [...videos]
      .sort((a, b) => b.viewCount - a.viewCount)
      .slice(0, 5);

    // Extract trends from titles (simple keyword frequency)
    const keywords = videos
      .flatMap((video) => video.title.toLowerCase().split(/\s+/))
      .filter((word) => word.length > 3);

    const keywordCount: Record<string, number> = {};
    keywords.forEach((word) => {
      keywordCount[word] = (keywordCount[word] || 0) + 1;
    });

    const trends = Object.entries(keywordCount)
      .sort(([, a], [, b]) => b - a)
      .slice(0, 10)
      .map(([word]) => word);

    return {
      totalVideos: videos.length,
      averageViews,
      topVideos,
      trends,
    };
  }

  /**
   * Generate report from analyzed data
   * @param analysisResults - Analysis results
   * @returns Generated report
   */
  generateReport(analysisResults: AnalysisResult): string {
    console.log('Generating report');

    const report: string[] = [];

    report.push('# YouTube Research Report');
    report.push('');
    report.push(`Generated: ${new Date().toISOString()}`);
    report.push('');

    report.push('## Summary');
    report.push(`- Total Videos Analyzed: ${analysisResults.totalVideos}`);
    report.push(`- Average Views: ${analysisResults.averageViews.toLocaleString()}`);
    report.push('');

    report.push('## Top Performing Videos');
    analysisResults.topVideos.forEach((video, index) => {
      report.push(`${index + 1}. **${video.title}**`);
      report.push(`   - Views: ${video.viewCount.toLocaleString()}`);
      report.push(`   - Likes: ${video.likeCount.toLocaleString()}`);
      report.push(`   - Video ID: ${video.id}`);
      report.push('');
    });

    report.push('## Trending Keywords');
    analysisResults.trends.forEach((keyword, index) => {
      report.push(`${index + 1}. ${keyword}`);
    });
    report.push('');

    report.push('---');
    report.push('*Generated by YouTubeResearchService*');

    return report.join('\n');
  }

  /**
   * Complete research workflow
   * @param query - Search query
   * @param maxResults - Maximum number of results
   * @param period - Time period filter
   * @returns Complete research report
   */
  async performResearch(query: string, maxResults = 20, period = 'all'): Promise<string> {
    // Search for videos
    const searchResults = await this.searchVideos(query, maxResults, period);

    // Get detailed info for each video
    const videoInfoPromises = searchResults.map((result) =>
      this.getVideoInfo(result.id)
    );
    const videos = await Promise.all(videoInfoPromises);

    // Analyze data
    const analysis = this.analyzeData(videos);

    // Generate report
    return this.generateReport(analysis);
  }
}

// Export for convenience
export { YouTubeAPIClient } from './client';
export * from './types';
