/**
 * YouTube Research Service
 *
 * Provides high-level YouTube research functionality including
 * video search, channel search, data analysis, and report generation.
 */

import { YouTubeAPIClient } from './client';
import type {
  VideoSearchResult,
  VideoInfo,
  ChannelSearchResult,
  AnalysisResult,
} from './types';

/**
 * Convert ISO 8601 duration to seconds
 * @param duration - ISO 8601 duration string (e.g., "PT1M30S")
 * @returns Duration in seconds
 */
function parseDuration(duration: string): number {
  const match = duration.match(/PT(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?/);
  if (!match) return 0;

  const hours = parseInt(match[1] || '0', 10);
  const minutes = parseInt(match[2] || '0', 10);
  const seconds = parseInt(match[3] || '0', 10);

  return hours * 3600 + minutes * 60 + seconds;
}

export class YouTubeResearchService {
  private client: YouTubeAPIClient;

  constructor(apiKey?: string) {
    this.client = new YouTubeAPIClient(apiKey);
    console.log('YouTubeResearchService initialized');
  }

  /**
   * Search for YouTube videos
   * @param query - Search query string
   * @param maxResults - Maximum number of results (default: 10)
   * @param period - Time period filter (day, week, month, year, all)
   * @returns Promise with search results
   */
  async searchVideos(query: string, maxResults = 10, period = 'all'): Promise<VideoSearchResult[]> {
    console.log(`Searching videos: ${query} (period: ${period})`);
    return await this.client.searchVideos(query, maxResults, period);
  }

  /**
   * Get video information
   * @param videoId - YouTube video ID
   * @returns Promise with video data
   */
  async getVideoInfo(videoId: string): Promise<VideoInfo> {
    console.log(`Getting video info: ${videoId}`);
    return await this.client.getVideoInfo(videoId);
  }

  /**
   * Search for YouTube channels
   * @param query - Search query string
   * @param maxResults - Maximum number of results (default: 10)
   * @returns Promise with channel results
   */
  async searchChannels(query: string, maxResults = 10): Promise<ChannelSearchResult[]> {
    console.log(`Searching channels: ${query}`);
    return await this.client.searchChannels(query, maxResults);
  }

  /**
   * Analyze video data
   * @param videos - Array of video data to analyze
   * @returns Analysis results
   */
  analyzeData(videos: VideoInfo[]): AnalysisResult {
    console.log(`Analyzing data for ${videos.length} videos`);

    if (videos.length === 0) {
      return {
        totalVideos: 0,
        averageViews: 0,
        topVideos: [],
        trends: [],
      };
    }

    const totalViews = videos.reduce((sum, video) => sum + video.viewCount, 0);
    const averageViews = Math.round(totalViews / videos.length);

    // Sort by view count and get top videos
    const topVideos = [...videos]
      .sort((a, b) => b.viewCount - a.viewCount)
      .slice(0, 5);

    // Extract trends from titles (simple keyword frequency)
    const keywords = videos
      .flatMap((video) => video.title.toLowerCase().split(/\s+/))
      .filter((word) => word.length > 3);

    const keywordCount: Record<string, number> = {};
    keywords.forEach((word) => {
      keywordCount[word] = (keywordCount[word] || 0) + 1;
    });

    const trends = Object.entries(keywordCount)
      .sort(([, a], [, b]) => b - a)
      .slice(0, 10)
      .map(([word]) => word);

    return {
      totalVideos: videos.length,
      averageViews,
      topVideos,
      trends,
    };
  }

  /**
   * Generate report from analyzed data
   * @param analysisResults - Analysis results
   * @returns Generated report
   */
  generateReport(analysisResults: AnalysisResult): string {
    console.log('Generating report');

    const report: string[] = [];

    report.push('# YouTube Research Report');
    report.push('');
    report.push(`Generated: ${new Date().toISOString()}`);
    report.push('');

    report.push('## Summary');
    report.push(`- Total Videos Analyzed: ${analysisResults.totalVideos}`);
    report.push(`- Average Views: ${analysisResults.averageViews.toLocaleString()}`);
    report.push('');

    report.push('## Top Performing Videos');
    analysisResults.topVideos.forEach((video, index) => {
      report.push(`${index + 1}. **${video.title}**`);
      report.push(`   - Views: ${video.viewCount.toLocaleString()}`);
      report.push(`   - Likes: ${video.likeCount.toLocaleString()}`);
      report.push(`   - Video ID: ${video.id}`);
      report.push('');
    });

    report.push('## Trending Keywords');
    analysisResults.trends.forEach((keyword, index) => {
      report.push(`${index + 1}. ${keyword}`);
    });
    report.push('');

    report.push('---');
    report.push('*Generated by YouTubeResearchService*');

    return report.join('\n');
  }

  /**
   * Calculate viral score for a video
   * @param video - Video information
   * @returns Viral score
   */
  private calculateViralScore(video: VideoInfo): number {
    if (!video.channelSubscriberCount || video.channelSubscriberCount === 0) {
      // 登録者数が取得できない場合は、再生回数のみで評価
      return video.viewCount / 10000;
    }

    // バズり度 = 再生回数 / (登録者数 + 1000)
    // +1000は、小規模チャンネルでも適切に評価されるためのオフセット
    const viralScore = video.viewCount / (video.channelSubscriberCount + 1000);

    // 投稿からの経過日数を考慮（最近の動画をより高く評価）
    const publishedDate = new Date(video.publishedAt);
    const now = new Date();
    const daysAgo = (now.getTime() - publishedDate.getTime()) / (1000 * 60 * 60 * 24);

    // 1週間以内の動画は2倍、1ヶ月以内は1.5倍のボーナス
    let timeBonus = 1.0;
    if (daysAgo <= 7) {
      timeBonus = 2.0;
    } else if (daysAgo <= 30) {
      timeBonus = 1.5;
    }

    return viralScore * timeBonus;
  }

  /**
   * Filter videos by duration type
   * @param videos - Array of video information
   * @param durationType - Type of videos (all, shorts, regular)
   * @returns Filtered videos
   */
  filterByDuration(videos: VideoInfo[], durationType: string = 'all'): VideoInfo[] {
    if (durationType === 'all') {
      return videos;
    }

    return videos.filter(video => {
      const durationInSeconds = parseDuration(video.duration);

      if (durationType === 'shorts') {
        // Shorts: 60秒以下
        return durationInSeconds <= 60;
      } else if (durationType === 'regular') {
        // 通常動画: 60秒より長い
        return durationInSeconds > 60;
      }

      return true;
    });
  }

  /**
   * Enrich videos with channel information and viral scores
   * @param videos - Array of video information
   * @param sortBy - Sort order (viral, viewCount, date)
   * @returns Enriched and sorted videos
   */
  async enrichAndSortVideos(videos: VideoInfo[], sortBy: string = 'viral'): Promise<VideoInfo[]> {
    console.log(`Enriching ${videos.length} videos with channel info...`);

    // チャンネルIDをユニークに取得
    const uniqueChannelIds = [...new Set(videos.map(v => v.channelId).filter(Boolean))];

    // チャンネル情報を一括取得（API効率化）
    const channelSubscribers: Record<string, number> = {};
    for (const channelId of uniqueChannelIds) {
      if (channelId) {
        const subscriberCount = await this.client.getChannelSubscriberCount(channelId);
        channelSubscribers[channelId] = subscriberCount;
      }
    }

    // 動画にチャンネル登録者数とバズり度を追加
    const enrichedVideos = videos.map(video => {
      const subscriberCount = video.channelId ? channelSubscribers[video.channelId] || 0 : 0;
      const enrichedVideo = {
        ...video,
        channelSubscriberCount: subscriberCount,
      };
      enrichedVideo.viralScore = this.calculateViralScore(enrichedVideo);
      return enrichedVideo;
    });

    // ソート
    if (sortBy === 'viral') {
      return enrichedVideos.sort((a, b) => (b.viralScore || 0) - (a.viralScore || 0));
    } else if (sortBy === 'viewCount') {
      return enrichedVideos.sort((a, b) => b.viewCount - a.viewCount);
    } else if (sortBy === 'date') {
      return enrichedVideos.sort((a, b) =>
        new Date(b.publishedAt).getTime() - new Date(a.publishedAt).getTime()
      );
    }

    return enrichedVideos;
  }

  /**
   * Complete research workflow
   * @param query - Search query
   * @param maxResults - Maximum number of results
   * @param period - Time period filter
   * @param sortBy - Sort order
   * @returns Complete research report
   */
  async performResearch(query: string, maxResults = 20, period = 'all', sortBy = 'viral'): Promise<string> {
    // Search for videos
    const searchResults = await this.searchVideos(query, maxResults, period);

    // Get detailed info for each video
    const videoInfoPromises = searchResults.map((result) =>
      this.getVideoInfo(result.id)
    );
    const videos = await Promise.all(videoInfoPromises);

    // Enrich with channel info and sort by viral score
    const enrichedVideos = await this.enrichAndSortVideos(videos, sortBy);

    // Analyze data
    const analysis = this.analyzeData(enrichedVideos);

    // Generate report
    return this.generateReport(analysis);
  }
}

// Export for convenience
export { YouTubeAPIClient } from './client';
export * from './types';
